[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
foundry = "http://127.0.0.1:8545"
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
optimism = "https://mainnet.optimism.io"
optimism_sepolia = "https://sepolia.optimism.io"
polygon = "https://polygon-rpc.com"
polygon_amoy = "https://rpc-amoy.polygon.technology"
